name: Deploy

on:
  workflow_dispatch:
    inputs:
      CLOUDFLARE_ACCOUNT_ID:
        description: "Cloudflare Account ID"
        default: ""
        required: true
        type: string
      CLOUDFLARE_API_TOKEN:
        description: "Cloudflare API Token"
        default: ""
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Apply D1 migrations
        run: npx wrangler d1 migrations apply database --remote
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}

      - name: Deploy worker
        run: npx wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
